volumes:
  db_volume:
  minio_data:

services:
  db:
    build: .docker/mysql
    ports:
      - "3306:3306"
    volumes:
      - db_volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: spring_web_sample_db
      MYSQL_PASSWORD: password
      MYSQL_USER: username
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"